package main

import (
	"fmt"
	"log"
	"myblog_last_new/pkg/api"
	"myblog_last_new/pkg/storage"
	"net/http"

	_ "myblog_last_new/docs" // docs is generated by Swag CLI, you have to import it.

	httpSwagger "github.com/swaggo/http-swagger"
)

// @title My Blog API
// @version 1.0
// @description This is a sample server for a blog application.
// @host localhost:8080
// @BasePath /
func main() {
	// 初始化数据库连接
	db, err := storage.ConnectDB()
	if err != nil {
		log.Fatalf("无法连接到数据库: %v", err)
	}
	defer db.Close()

	// 初始化数据库表
	if err := storage.InitDB(db); err != nil {
		log.Fatalf("数据库表初始化失败: %v", err)
	}

	// 设置路由
	mux := http.NewServeMux()
	api.RegisterRoutes(mux, db)

	// Swagger UI
	mux.Handle("/swagger/", httpSwagger.WrapHandler)

	// 启动服务器
	fmt.Println("服务器正在端口 8080 启动...")
	fmt.Println("API 文档地址: http://localhost:8080/swagger/index.html")
	if err := http.ListenAndServe(":8080", mux); err != nil {
		log.Fatalf("无法启动服务器: %v", err)
	}
}
