package main

import (
	"fmt"
	"log"
	"myblog_last_new/pkg/api"
	"myblog_last_new/pkg/storage"
	"net/http"
	"os"

	_ "myblog_last_new/docs" // docs is generated by Swag CLI, you have to import it.

	httpSwagger "github.com/swaggo/http-swagger"
)

// @title My Blog API
// @version 1.0
// @description This is a sample server for a blog application.
// @host localhost:8080
// @BasePath /
func main() {
	// 初始化数据库连接
	db, err := storage.ConnectDB()
	if err != nil {
		log.Fatalf("无法连接到数据库: %v", err)
	}
	defer db.Close()

	// 初始化数据库表
	if err := storage.InitDB(db); err != nil {
		log.Fatalf("数据库表初始化失败: %v", err)
	}

	// 设置路由
	mux := http.NewServeMux()
	api.RegisterRoutes(mux, db)

	// Swagger UI
	mux.Handle("/swagger/", httpSwagger.WrapHandler)

	// 静态文件服务
	fs := http.FileServer(http.Dir("static"))
	mux.Handle("/static/", http.StripPrefix("/static/", fs))

	// 从环境变量获取端口，默认8080
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	// 启动服务器
	fmt.Printf("服务器正在端口 %s 启动...\n", port)
	fmt.Printf("API 文档地址: http://localhost:%s/swagger/index.html\n", port)
	fmt.Printf("分类管理页面: http://localhost:%s/static/category.html\n", port)
	if err := http.ListenAndServe(":"+port, mux); err != nil {
		log.Fatalf("无法启动服务器: %v", err)
	}
}
